"""Initial schema: all 9 tables from db/schema.sql, plus the fixed pipeline stages.

Revision ID: 0001
Revises: 
Create Date: 2026-09-15 19:48:34.549923

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models.stage import PIPELINE_STAGES


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('sort_order')
    )
    # Fixed, ordered pipeline. Lookup rows ship with the schema, not the seed script.
    op.bulk_insert(
        sa.table('stages', sa.column('key'), sa.column('name'), sa.column('sort_order')),
        [{'key': k, 'name': n, 'sort_order': o} for k, n, o in PIPELINE_STAGES],
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('csm', 'implementation_analyst', 'engineer', 'manager')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kickoff_date', sa.Date(), nullable=False),
    sa.Column('target_go_live_date', sa.Date(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("segment IN ('enterprise', 'mid_market', 'smb')", name='ck_clients_segment'),
    sa.CheckConstraint('contract_value >= 0', name='ck_clients_contract_value'),
    sa.CheckConstraint('target_go_live_date >= kickoff_date', name='ck_clients_go_live_after_kickoff'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_current_stage_id'), ['current_stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_clients_target_go_live', ['target_go_live_date'], unique=False)

    op.create_table('client_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('exited_at IS NULL OR exited_at >= entered_at', name='ck_stage_history_dates'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_stage_history_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_stage_history_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index('ux_stage_history_open', ['client_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'), sqlite_where=sa.text('exited_at IS NULL'))

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('held_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('ix_meetings_client_held', ['client_id', 'held_at'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(status = 'done') = (completed_at IS NOT NULL)", name='ck_milestones_done_completed'),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'done')", name='ck_milestones_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_milestones_open_due', ['due_date'], unique=False, postgresql_where=sa.text("status <> 'done'"), sqlite_where=sa.text("status <> 'done'"))
        batch_op.create_index(batch_op.f('ix_milestones_owner_id'), ['owner_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_client_created', ['client_id', 'created_at'], unique=False)

    op.create_table('blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('external_ref', sa.String(length=40), nullable=True),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_blockers_severity'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= opened_at', name='ck_blockers_dates'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blockers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockers_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index('ix_blockers_open', ['client_id', 'severity', 'opened_at'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'), sqlite_where=sa.text('resolved_at IS NULL'))
        batch_op.create_index(batch_op.f('ix_blockers_owner_id'), ['owner_id'], unique=False)

    op.create_table('meeting_attendees',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id')
    )
    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.create_index('ix_meeting_attendees_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_attendees_user_id')

    op.drop_table('meeting_attendees')
    with op.batch_alter_table('blockers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockers_owner_id'))
        batch_op.drop_index('ix_blockers_open', postgresql_where=sa.text('resolved_at IS NULL'), sqlite_where=sa.text('resolved_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_blockers_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_blockers_client_id'))

    op.drop_table('blockers')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_client_created')

    op.drop_table('notes')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_owner_id'))
        batch_op.drop_index('ix_milestones_open_due', postgresql_where=sa.text("status <> 'done'"), sqlite_where=sa.text("status <> 'done'"))
        batch_op.drop_index(batch_op.f('ix_milestones_client_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_meetings_client_held')

    op.drop_table('meetings')
    with op.batch_alter_table('client_stage_history', schema=None) as batch_op:
        batch_op.drop_index('ux_stage_history_open', postgresql_where=sa.text('exited_at IS NULL'), sqlite_where=sa.text('exited_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_client_stage_history_stage_id'))
        batch_op.drop_index(batch_op.f('ix_client_stage_history_client_id'))

    op.drop_table('client_stage_history')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_target_go_live')
        batch_op.drop_index(batch_op.f('ix_clients_owner_id'))
        batch_op.drop_index(batch_op.f('ix_clients_current_stage_id'))

    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('stages')
    # ### end Alembic commands ###
